import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/contexts/AuthContext'
import type { Product } from '@/lib/types'

type Scheduled = { id:string; product_id:string; quantity:number; scheduled_for:string; status:string; notes:string|null; products?: {name:string} }

export default function ScheduledOrders() {
  const { user } = useAuth(); const [products,setProducts]=useState<Product[]>([]); const [items,setItems]=useState<Scheduled[]>([]); const [productId,setProductId]=useState(''); const [quantity,setQuantity]=useState(1); const [when,setWhen]=useState(''); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false)
  async function load(){ if(!user)return; const [p,s]=await Promise.all([supabase.from('products').select('id,name,description,base_price,image_url,is_available,out_of_stock,is_recommended,category_id').eq('is_available',true).eq('out_of_stock',false).order('name'),supabase.from('scheduled_orders').select('*,products(name)').order('scheduled_for',{ascending:true})]); setProducts((p.data??[]) as Product[]); setItems((s.data??[]) as Scheduled[]); if(!productId&&p.data?.[0])setProductId(p.data[0].id) }
  useEffect(()=>{void load()},[user])
  async function schedule(){ if(!user||!productId||!when)return; setSaving(true); await supabase.from('scheduled_orders').insert({customer_id:user.id,product_id:productId,quantity,scheduled_for:new Date(when).toISOString(),notes:notes||null}); setNotes('');setQuantity(1);setSaving(false);void load() }
  async function cancel(id:string){await supabase.from('scheduled_orders').update({status:'cancelled'}).eq('id',id);void load()}
  return <main className="min-h-screen px-6 py-10 max-w-3xl mx-auto"><div className="flex justify-between mb-8"><div><p className="text-xs tracking-[.2em] text-espresso-light">COFFEE HOUSE</p><h1 className="font-display text-4xl">Schedule your next cup.</h1></div><Link to="/dashboard" className="text-sm underline">Dashboard</Link></div><div className="border border-line p-6 space-y-4 mb-8"><h2 className="font-display text-xl">Plan ahead</h2><select value={productId} onChange={e=>setProductId(e.target.value)} className="w-full border border-line px-3 py-3 bg-white">{products.map(p=><option key={p.id} value={p.id}>{p.name} · ₹{p.base_price}</option>)}</select><div className="grid sm:grid-cols-2 gap-3"><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className="border border-line px-3 py-3"/><input type="number" min="1" max="10" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="border border-line px-3 py-3"/></div><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Note for your future self…" className="w-full border border-line px-3 py-3"/><button onClick={schedule} disabled={saving||!when||!productId} className="bg-espresso text-cream px-5 py-3 text-sm disabled:opacity-50">{saving?'Scheduling…':'Schedule order'}</button><p className="text-xs text-espresso-light">Scheduling reserves the intention; staff will confirm preparation when the time arrives.</p></div><section><h2 className="font-display text-2xl mb-3">Upcoming</h2><div className="space-y-3">{items.length===0&&<p className="text-sm text-espresso-light">Nothing scheduled yet.</p>}{items.map(i=><div key={i.id} className="border border-line p-4 flex justify-between gap-4"><div><p className="font-display">{i.quantity}× {i.products?.name??'Coffee'}</p><p className="text-sm text-espresso-light">{new Date(i.scheduled_for).toLocaleString()}</p>{i.notes&&<p className="text-xs mt-1">{i.notes}</p>}</div>{i.status==='scheduled'&&<button onClick={()=>cancel(i.id)} className="text-xs text-burgundy underline">Cancel</button>}</div>)}</div></section></main>
}
