import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '@/lib/supabase'

export default function StaffCopilot(){
 const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [answer,setAnswer]=useState(''); const [context,setContext]=useState<Record<string,unknown>>({})
 useEffect(()=>{ Promise.all([supabase.from('orders').select('id,status,total_amount,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('products').select('id,name,out_of_stock,is_available').limit(100),supabase.from('scheduled_orders').select('id,status,scheduled_for').order('scheduled_for').limit(100)]).then(([o,p,s])=>setContext({orders:o.data||[],products:p.data||[],scheduled_orders:s.data||[]})) },[])
 async function ask(q=input){if(!q.trim()||loading)return;setLoading(true);setAnswer('');try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'staff',messages:[{role:'user',content:q}],context})});const d=await r.json();setAnswer(r.ok?d.reply:d.error)}catch{setAnswer('AI Copilot is unavailable right now.')}finally{setLoading(false)}}
 return <main className="min-h-screen bg-[#090806] text-[#f5ead8] px-4 py-8 md:px-10"><div className="max-w-6xl mx-auto"><nav className="flex justify-between mb-12"><Link to="/staff/dashboard" className="font-black tracking-[.2em]">STAFF / COPILOT</Link><Link to="/staff/dashboard" className="opacity-60">Back ↗</Link></nav><span className="text-xs tracking-[.3em] opacity-50">AI OPERATIONS INTELLIGENCE</span><h1 className="text-5xl md:text-7xl font-black mt-4">Ask the<br/><i>business.</i></h1><div className="mt-10 grid lg:grid-cols-[.8fr_1.2fr] gap-6"><div className="rounded-3xl border border-white/10 p-6 bg-white/[.03]"><p className="opacity-60">Try</p><div className="space-y-2 mt-4">{['What needs attention right now?','Are there unusual order patterns?','Which products look risky?','Give me a shift handover summary.'].map(q=><button key={q} onClick={()=>{setInput(q);ask(q)}} className="block w-full text-left rounded-2xl bg-white/5 hover:bg-white/10 p-4">{q}</button>)}</div></div><div className="rounded-3xl border border-white/10 p-6 bg-white/[.03] min-h-[420px]"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask an operational question…" className="w-full h-32 bg-transparent outline-none resize-none"/><button onClick={()=>ask()} className="rounded-full bg-[#f1d2a5] text-black px-6 py-3 font-bold">Analyze ↗</button><div className="mt-8 border-t border-white/10 pt-6 whitespace-pre-wrap leading-relaxed">{loading?'Analyzing live dashboard context…':answer||'Your operational analysis will appear here.'}</div></div></div></div></main>
}
